name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    defaults:
      run:
        working-directory: ./example/
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          targetBranch: gh-page
          baseHref: /
         
